# Generated by Django 4.2 on 2023-04-20 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_remove_customer_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='first_name',
            new_name='name',
        ),
    ]
