# Generated by Django 4.0 on 2023-08-03 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['title'], 'verbose_name': 'Пост', 'verbose_name_plural': 'Посттар'},
        ),
    ]
