# Generated by Django 4.2 on 2023-04-20 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_alter_employee_executor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='email',
        ),
    ]
