# Generated by Django 4.0 on 2023-08-03 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_remove_employee_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'Орындаушы', 'verbose_name_plural': 'Орындаушылар'},
        ),
    ]
