# Generated by Django 4.2 on 2023-10-07 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_birthday_user_group_user_specialty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Супер әкімші'), ('executor', 'Орындаушы'), ('auditor', 'Аудитор')], default='executor', max_length=20),
        ),
    ]
