# Generated by Django 4.2 on 2023-05-15 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('by_pass_sheet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bypasssheetfield',
            name='bypass_sheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bypass_sheet_field', to='by_pass_sheet.bypasssheet'),
        ),
    ]
