# Generated by Django 4.2 on 2023-05-15 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('by_pass_sheet', '0002_alter_bypasssheetfield_bypass_sheet'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bypasssheet',
            options={'verbose_name': 'Алаушы тізімі', 'verbose_name_plural': 'Алаушы тізімдер'},
        ),
    ]
