# Generated by Django 4.2 on 2023-05-16 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('by_pass_sheet', '0003_alter_bypasssheet_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bypasssheet',
            options={'verbose_name': 'Обходной лист', 'verbose_name_plural': 'Обходные листы'},
        ),
    ]
